// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Crawler struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Certificate string `json:"certificate"`
}

type NewCrawler struct {
	Name        string `json:"name"`
	Certificate string `json:"certificate"`
}
