// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Crawler struct {
	ID          string `json:"id"`
	CreatedAt   string `json:"createdAt"`
	Name        string `json:"name"`
	Certificate string `json:"certificate"`
}

type Label struct {
	ID        string `json:"id"`
	CrawlerID string `json:"crawlerID"`
	Name      string `json:"name"`
}

type NewCrawler struct {
	Name        string `json:"name"`
	Certificate string `json:"certificate"`
}
