// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type InfoResponse struct {
	Application          string   `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	Environment          string   `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Build                string   `protobuf:"bytes,4,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{1}
}

func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (m *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(m, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *InfoResponse) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *InfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InfoResponse) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

type UptimeResponse struct {
	Duration             string   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UptimeResponse) Reset()         { *m = UptimeResponse{} }
func (m *UptimeResponse) String() string { return proto.CompactTextString(m) }
func (*UptimeResponse) ProtoMessage()    {}
func (*UptimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{2}
}

func (m *UptimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UptimeResponse.Unmarshal(m, b)
}
func (m *UptimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UptimeResponse.Marshal(b, m, deterministic)
}
func (m *UptimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UptimeResponse.Merge(m, src)
}
func (m *UptimeResponse) XXX_Size() int {
	return xxx_messageInfo_UptimeResponse.Size(m)
}
func (m *UptimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UptimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UptimeResponse proto.InternalMessageInfo

func (m *UptimeResponse) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func init() {
	proto.RegisterType((*Void)(nil), "api.Void")
	proto.RegisterType((*InfoResponse)(nil), "api.InfoResponse")
	proto.RegisterType((*UptimeResponse)(nil), "api.UptimeResponse")
}

func init() {
	proto.RegisterFile("system.proto", fileDescriptor_86a7260ebdc12f47)
}

var fileDescriptor_86a7260ebdc12f47 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0x6c, 0x6d, 0x8d, 0xf6, 0x59, 0x04, 0xa3, 0x87, 0xd0, 0x53, 0xc9, 0x41, 0x44, 0xa4, 0x07,
	0xfd, 0x0a, 0xaf, 0x15, 0x3d, 0x79, 0x49, 0x6d, 0x84, 0x07, 0x6d, 0x12, 0x92, 0xb4, 0xb0, 0xd7,
	0xfd, 0xf2, 0x25, 0x29, 0x5b, 0xb2, 0xb7, 0x99, 0xc9, 0xe4, 0xbd, 0x99, 0x07, 0xb5, 0x3b, 0x38,
	0x2f, 0xe7, 0xce, 0x58, 0xed, 0x35, 0x2d, 0x84, 0x41, 0x4e, 0xa0, 0xfc, 0xd1, 0x38, 0xf2, 0x63,
	0x0e, 0xf5, 0xa7, 0xfa, 0xd7, 0xbd, 0x74, 0x46, 0x2b, 0x27, 0x69, 0x0b, 0x77, 0xc2, 0x98, 0x09,
	0xff, 0x84, 0x47, 0xad, 0x58, 0xde, 0xe6, 0x2f, 0x55, 0x9f, 0x4a, 0xc1, 0x21, 0xd5, 0x8a, 0x56,
	0xab, 0x59, 0x2a, 0xcf, 0xae, 0x36, 0x47, 0x22, 0x51, 0x06, 0x37, 0xab, 0xb4, 0x2e, 0xfc, 0x2f,
	0xe2, 0xeb, 0x99, 0xd2, 0x27, 0xb8, 0x1e, 0x16, 0x9c, 0x46, 0x56, 0x46, 0x7d, 0x23, 0xfc, 0x0d,
	0xee, 0xbf, 0x8d, 0xc7, 0x59, 0xee, 0x29, 0x1a, 0xb8, 0x1d, 0x17, 0x9b, 0x46, 0xd8, 0xf9, 0xfb,
	0x2f, 0x90, 0xaf, 0xd8, 0x87, 0x3e, 0x43, 0x19, 0xb2, 0xd3, 0xaa, 0x13, 0x06, 0xbb, 0xd0, 0xa7,
	0x79, 0x88, 0x30, 0x6d, 0xc4, 0x33, 0xfa, 0x0a, 0x64, 0x9b, 0x9f, 0x3a, 0x1f, 0x23, 0xbc, 0xdc,
	0xcb, 0xb3, 0x81, 0xc4, 0x23, 0x7d, 0x9c, 0x02, 0x00, 0x00, 0xff, 0xff, 0x19, 0x52, 0x9c, 0x25,
	0x34, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SystemClient is the client API for System service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemClient interface {
	Info(ctx context.Context, in *Void, opts ...grpc.CallOption) (*InfoResponse, error)
	Uptime(ctx context.Context, in *Void, opts ...grpc.CallOption) (*UptimeResponse, error)
}

type systemClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemClient(cc grpc.ClientConnInterface) SystemClient {
	return &systemClient{cc}
}

func (c *systemClient) Info(ctx context.Context, in *Void, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/api.System/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) Uptime(ctx context.Context, in *Void, opts ...grpc.CallOption) (*UptimeResponse, error) {
	out := new(UptimeResponse)
	err := c.cc.Invoke(ctx, "/api.System/Uptime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServer is the server API for System service.
type SystemServer interface {
	Info(context.Context, *Void) (*InfoResponse, error)
	Uptime(context.Context, *Void) (*UptimeResponse, error)
}

// UnimplementedSystemServer can be embedded to have forward compatible implementations.
type UnimplementedSystemServer struct {
}

func (*UnimplementedSystemServer) Info(ctx context.Context, req *Void) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (*UnimplementedSystemServer) Uptime(ctx context.Context, req *Void) (*UptimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Uptime not implemented")
}

func RegisterSystemServer(s *grpc.Server, srv SystemServer) {
	s.RegisterService(&_System_serviceDesc, srv)
}

func _System_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.System/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).Info(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_Uptime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).Uptime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.System/Uptime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).Uptime(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _System_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.System",
	HandlerType: (*SystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _System_Info_Handler,
		},
		{
			MethodName: "Uptime",
			Handler:    _System_Uptime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}
